### ISSUE TITLE
Capnp-ts crashes when parsing messages with unset text fields

### ISSUE THREAD

**Issue by erikmchut** [jdiaz5513/capnp-ts#108]
We pushed a new version of our logs server that had some new text fields in our capnp schema and if fell over in production when receiving messages from old clients. These old clients were not setting the new fields (expected), but the new server would fail validation when receiving these old messages.

The errors were all of the form:

CAPNP-TS024 Attempted to convert pointer Pointer_1@0x00000018,[5e 00 00 00 01 00 00 00],limit:0x7ffffffa to a 1 type.
CAPNP-TS024 Attempted to convert pointer Pointer_3@0x00000018,[5e 00 00 00 03 00 00 00],limit:0x7ffffffa to a 1 type.
CAPNP-TS024 Attempted to convert pointer Pointer_3@0x00000018,[5e 00 00 00 03 00 00 00],limit:0x7ffffffa to a 1 type.
CAPNP-TS024 Attempted to convert pointer Pointer_3@0x00000018,[5e 00 00 00 03 00 00 00],limit:0x7ffffffa to a 1 type.
CAPNP-TS024 Attempted to convert pointer Pointer_3@0x00000018,[5e 00 00 00 03 00 00 00],limit:0x7ffffffa to a 1 type.
CAPNP-TS024 Attempted to convert pointer Pointer_3@0x00000018,[5e 00 00 00 03 00 00 00],limit:0x7ffffffa to a 1 type.

We tracked the issue down in the capnp-ts source, which we are diagnosing as a null-pointer dereference issue. We've posted PR #107 with what we believe is the fix.

I'd like to have provided a minimal repro example, but we've only been able to reproduce with our large log schema. Smaller messages don't have enough data in the source segment to cause the null-dereference to get access to bad data.

**Comment by cmbartschat** [comment]
@jdiaz5513  It appears the fix for this in struct.ts did not propagate into struct.js in the 0.3.1 release. Apologies if I missed something in my change which would've done so.

**Comment by jdiaz5513** [comment]
I botched the publish for 0.3.1 (hence the patch in #109 to avoid this next time).

I'll unpublish the bad rev and hopefully get 0.3.2 up in a few hours.

**Comment by jdiaz5513** [comment]
0.4.0 (not 0.3.2) is up now. Give it a whirl and reopen if this issue still recurs.
