### ISSUE TITLE
Are you open to moving your packing algorithm to its own NPM module?

### ISSUE THREAD

**Issue by popham** [jdiaz5513/capnp-ts#112]
I'm looking to steal your implementation of packing. Would you be receptive to a PR that rearranges your repo to publish packing to NPM as its own package? My use case is a Cap'n Proto implementation for Flow, but the subset of type annotations used in [capnp-ts/src/serialization/packing.ts](https://github.com/jdiaz5513/capnp-ts/blob/699685f5b7e686dee7ca759b7dbfbdd2f3280716/packages/capnp-ts/src/serialization/packing.ts) appear compatible with Flow.

**Comment by jdiaz5513** [comment]
Sure, give it a go! I'll propose the name as `capnp-packing` and if the PR
lands well after review I'd be happy to publish it alongside the rest. I
don't know what a hybrid typescript + flow library needs to look like, but
I can at least verify the TS parts are done right

**Comment by popham** [comment]
Never mind. I didn't notice TypeScript's `enum` constructs. I've got a `@capnp-js` on NPM where I can publish without colliding with anything that you might do. In the meantime I've already grabbed `@capnp-js` on NPM, so I'll publish my ported version there (`@capnp-js/packing` probably).
