### ISSUE TITLE
use gulp instead of make

### ISSUE THREAD

**Issue by jdiaz5513** [jdiaz5513/capnp-ts#29]
Makefiles are hard to understand/write (sorry, it's true), and they're UNIX only.

**Comment by ishitatsuyuki** [comment]
I'm having a hard time integrating your test framework, `node-tap` with gulp. Is it something you use by favor, or should I migrate to a more widely used one like Jasmine?

**Comment by efokschaner** [comment]
@jdiaz5513 I wanted to throw in my perspective on the package builds which isn't so much a make Vs gulp thing but now seems like a good time to bring it up: I don't think the monorepo needs to be so prescriptive about the way each package is built. I would prefer to see the repo delegate to a make, or npm task, or gulp task or whatever, entry point in each package. A build contract or interface, so to speak. We can have convention and shared utilities for each package's build to share what makes sense but the packages could benefit perhaps from less top down "this is how you build".

**Comment by jdiaz5513** [comment]
It looks like a bit of a pain to integrate node-tap into gulp; it will likely need a plugin. The whole "everything is a stream" idea is what kills me about gulp.

That said, we don't need "integration" - using gulp to execute shell commands is totally fine.

Make sure you're using gulp 4, and try this helper I wrote for a different library:

```javascript
var spawn = require('child_process').spawn;
var util = require('gulp-util');

/**
 * Handy utility to spawn a shell command in a gulp-friendly way.
 *
 * @export
 * @param {string} taskName A name for the task currently being run; this is used for printing error messages.
 * @param {string} path The path to the executable to run.
 * @param {string[]} [args] Arguments to pass to the executable.
 * @param {Object} [opts] Additional options to pass to `child_process.spawn`. It also takes an additional option
 * `verbose` to control printing to stdout (defaults to false).
 * @param {ProcessCallback} [cb] Optional callback to modify the process before returning (for piping stdio
 * streams).
 * @returns {Promise<string>} A promise that resolves with the combined stdout and stderr output for the process. The
 * Promise will reject if the command exits with a nonzero exit code.
 */

function spawnTask(taskName, path, args, opts, cb) {

  var failed = false;
  var out = '';

  /**
   * @param {string} data
   */

  function appendData(data) {

    out += data;

  }

  var verbose = opts && opts.verbose;
  opts = Object.assign({}, opts, {env: process.env, stdio: verbose ? 'inherit' : 'pipe'});
  delete opts.verbose;

  return new Promise((resolve, reject) => {

    if (verbose) util.log('Running command:', path, args.join(' '));

    var ps = spawn(path, args, opts).on('error', (err) => {

      reject(new util.PluginError(taskName, err));

      failed = true;

    }).on('exit', (err) => {

      if (failed) return;

      if (err) {

        reject(new util.PluginError(taskName, out ? out : 'Command failed with exit code ' + err));

        return;

      }

      resolve(out);

    });

    if (ps.stdout) ps.stdout.on('data', appendData);

    if (ps.stderr) ps.stderr.on('data', appendData);

    if (cb) cb(ps);

  });

}
```

To use it:

```javascript
function runTests() {

  return spawnTask('runTests', '/path/to/node-tap', ['--some', '--args']);

}

gulp.task('runTests', runTests);
```

**Comment by jdiaz5513** [comment]
@efokschaner You make a good point; it's overly presumptive that future packages in the monorepo will need the same tooling.

@ishitatsuyuki It's a good idea to plan to make each package someone standalone with their own gulp tasks (so if you run gulp from within the package, it'll do the right thing). Have a top level gulpfile.js for running these tasks across all packages.

Each package should implement gulp tasks for each one of the top level make targets, documented [here](https://github.com/jdiaz5513/capnp-ts#build-targets).

**Comment by ishitatsuyuki** [comment]
I'm not sure if I agree with that. I think it's very likely to end up with only the two packages we currently have, and splitting code sacrifices reuse.

**Comment by jdiaz5513** [comment]
Well. Ultimately the person writing the build tooling will know the best
thing to do, so I'll trust you to take it in the direction you feel makes
the most sense.

Once a PR comes around we can talk about the finer details. Ideally this
won't be a very large or complicated repo so hopefully there won't be a lot
to talk about. :)

**Comment by efokschaner** [comment]
Fyi @ishitatsuyuki I'm soon introducing one more fairly similar package `capnpc-js`, and another that is quite dissimilar, a vanilla js example package using `capnpc-js`. That said, I'm fine with some prescriptiveness but i will need to make some exceptions for the vanilla js examples package.

**Comment by ishitatsuyuki** [comment]
If possible, please take a look at my WIP at #31.

I agree that Gulp modularity is good; but I currently ended up creating only one as it's how Makefile is organized currently and the transpile doesn't work yet (thus, only capnp-ts is built and tested). I believe the current source is easy to refactor, so feel free to split it up when the time comes.
