### ISSUE TITLE
I'd like to help

### ISSUE THREAD

**Issue by efokschaner** [jdiaz5513/capnp-ts#3]
Wondering if we can split up some of the work? Maybe with the schema compiler, for example? Let me know if you'd like help with that or anything else.

**Comment by jdiaz5513** [comment]
I appreciate the offer! I have a lot of unpushed work sitting on my computer now that needs cleaning up, and I think generally it's going to be hard to have multiple contributors until the v1 schema compiler is ready (I actually already have a **very** broken schema compiler at the moment, but it needs a few more days of work).

I'll keep you posted.

**Comment by jdiaz5513** [comment]
@efokschaner I've got a concrete thing for you to help with if you're still willing!

Check out #5 and see if you can figure it out; going to close this issue now that we have a schema compiler. :)

**Comment by efokschaner** [comment]
I'll take look on Saturday (ie today but after I've slept :D)
