### ISSUE TITLE
coverage reports are broken

### ISSUE THREAD

**Issue by jdiaz5513** [jdiaz5513/capnp-ts#36]
Running `gulp coverage` definitely does the wrong thing; it will make separate test runs for each package then generate the coverage report for the _last_ package that was run.

That task needs some deep rethinking. The way `node-tap` is supposed to work for coverage is you run it once with nyc enabled, then again to generate the actual coverage report. The only way to make this work across multiple packages is to combine the tests into a single run (so gather all the spec files from `capnp-ts` and `capnpc-ts` and run them together) before generating the coverage report.

Additionally, it looks like there's additional trouble with the source maps generated by `gulp-sourcemaps`. They don't set `sourceRoot` so nyc doesn't know how to reference the original source. See https://github.com/istanbuljs/nyc/issues/359#issuecomment-301285742.

**Comment by jdiaz5513** [comment]
@ishitatsuyuki I may tackle this myself tonight or tomorrow since it's interfering with my goal of 100% coverage for the critical code sections.

**Comment by ishitatsuyuki** [comment]
I think a quick fix would be merging two test-cov tasks, and use a universal glob for it.

**Comment by ishitatsuyuki** [comment]
I have fixed the sourceRoot thing currently in a new branch: https://github.com/ishitatsuyuki/capnp-ts/tree/gulp-try2

I will fix the remaining issues like merging the test script list tomorrow, and open a PR to revive properly written Gulpfile.
