### ISSUE TITLE
should not cache node_modules in travis

### ISSUE THREAD

**Issue by efokschaner** [jdiaz5513/capnp-ts#40]
Are we sure we want to cache all the node_modules folders?
Builds would be potentially better isolated and still well cached if we only cached the yarn cache itself ($HOME/.cache/yarn) see: https://docs.travis-ci.com/user/caching/#yarn-cache
I could see packages in node_modules from previous runs potentially creating build weirdness (lack of idempotence).

If we decide we DO want to cache all node_modules folders, then I wonder if `directories` supports patterns, it wasn't clear from docs.

**Comment by jdiaz5513** [comment]
Agree, I overlooked this when reviewing the PR that brought it in.

Caching `node_modules` directly is quite dangerous.

**Comment by efokschaner** [comment]
Yeah I didn't even know about travis caching until I had to reconcile the changes with my new stuff and looked up the docs. Sounds nifty though, if used right.

**Comment by ishitatsuyuki** [comment]
No, it isn't dangerous. It actually makes the CI much faster. Yarn is quite good at keeping the installation clean.

**Comment by jdiaz5513** [comment]
I really should RTFM more often. I was thinking this did something else, but after checking the travis docs on cache behavior this is fine.

It's basically the same as having a local checkout that you update on every pull (there were versions of npm where this was **not** okay and `rm -rf node_modules` was common but that's ancient history now).
