### ISSUE TITLE
Question about "bundling" capnpc

### ISSUE THREAD

**Issue by efokschaner** [jdiaz5513/capnp-ts#41]
I was curious about this idea in the readme:
> NOTE: At some point in the future the capnpc-ts package may build the capnpc binary as a native dependency, making this step somewhat unnecessary.

Given that serialisation / rpc protocols are often used to talk across technology stacks I suspect that most users of this would (at least eventually) need to have a capnp setup independent of the stuff we're providing here. Therefore I think it's a bit odd/niche to provide such a utility.

Are any other languages / compiler plugins doing such things?
What are the motivations for doing this?

**Comment by jdiaz5513** [comment]
Funny, I was just mulling over what this would look like recently.

I was primarily thinking about beginner JS folk who don't understand what a C++ is or how to install packages; but truth be told it would be difficult for them to use a library like this regardless (especially at this stage, for sure).

I'm going to drop it from the README.
