### ISSUE TITLE
Create labels for different kinds of issues

### ISSUE THREAD

**Issue by efokschaner** [jdiaz5513/capnp-ts#43]
This started with me thinking that I frequently have questions that i don't feel justified spamming up the issues system with. I was about to suggest we open some alternative discussion channel.
But then I realised we'd probably need to sub-categorise things properly anyway unless we had as many systems for discussion  as there were types of things that can come up therefore I'm leaning towards saying let's do issues but with better tagging.

Here are some obvious category suggestions just to get started:
- Bug reports
- Todo's
- Support requests (can be used for both external and internal development help)
- Suggestions

**Comment by jdiaz5513** [comment]
I took a first pass at organizing the labels for now.

Right now in early days I'm fine with github issues for general questions and discussion.

In the future if the conversation picks up a lot of steam (and users) something more real-time will be nice.
