### ISSUE TITLE
TS->JS schema transpilation does not work

### ISSUE THREAD

**Issue by jdiaz5513** [jdiaz5513/capnp-ts#5]
The schema compiler (`capnpc-ts`) currently has all the code necessary to transpile the emitted .ts file into .js using the TypeScript compiler API directly, but I have failed to get it to actually _work_ without choking on the `capnp-ts` import.

The compiler configuration is here: https://github.com/jdiaz5513/capnp-ts/blob/b5cb174a990c5fb45288289bceaf17362c19b778/packages/capnpc-ts/src/constants.ts#L54-L66

The transpile step is commented out here: https://github.com/jdiaz5513/capnp-ts/blob/b5cb174a990c5fb45288289bceaf17362c19b778/packages/capnpc-ts/src/index.ts#L61-L62

I tried using the `baseUrl` and `paths` options to no avail; but it's entirely possible I missed something.

Ideally, the TypeScript compiler should load `capnpc-ts`'s copy of `capnp-ts` from `node_modules`, and not depend on `capnp-ts` being available from the path it's compiling from... or something.

**Comment by efokschaner** [comment]
Just familiarising myself with things. I'm thinking that being able to emit js should maybe not be the responsibility of capnpc-ts. As the schema compiler for TS its job is done when you have a set of valid TS modules that you can use directly in your TS code. This means when serving TS users we don't need to know what their TS->JS compilation configuration needs are, they handle that downstream.

Obviously it's pretty low hanging fruit to then also release a capnpc-js tool that uses capnpc-ts internally, and we should do that. It would work by running capnpc-ts to an intermediary dir, then set up some stock tsc configuration and run the typescript compiler to produce js (basically as you were trying to do here). If you'd like I could start working on that layer to build out a direct to JS version, although as a customer I have more use for the TS than the JS capnpc. So I might have a better feel for other features, but if this is a good priority I'm keen to help.

Let me know if that seems off architecturally, still familiarising myself after all.

**Comment by jdiaz5513** [comment]
No, that's totally fair. I just know a lot of folks are going to want a pure JS schema compiler one way or another, but it can wait for now.

Having it be a separate package is probably best (`capnpc-js`?).

**Comment by jdiaz5513** [comment]
@efokschaner I know it sounds boring, but I could use some help with test coverage on the schema compiler - I'm currently working on coverage for the main library.

It's a decent way to get familiar with that part of the code; just beware that the TypeScript compiler API is barely documented so... good luck!

**Comment by efokschaner** [comment]
Adding tests sounds fine to me. And I've actually got a few dozen hours under my belt of interfacing with the tsc lib. That said, should tests fuss with using the tsc lib, or should we just invoke tsc through the command line?

Regarding `capnpc-js` there is a project in that space already: https://github.com/capnp-js . I don't think this should stop us releasing a potentially better version based on capnp-ts, but it's worth taking a look and maybe even reaching out to the author to create a plan to avoid creating ambiguity for users, whatever that might look like.

One interesting thing to note is that developing `capnpc-js` and adding tests for that would indirectly provide test coverage of `capnpc-ts`. I'm a big fan of writing really end to end tests when starting out, i feel it gets the most coverage for your investment. So maybe we could start out that way?

**Comment by jdiaz5513** [comment]
I like that plan. Look forward to seeing your work!

I'll reach out to the capnp-js maintainer(s) later and see how we can work
this all together. Given the utter lack of activity from that end I don't
exactly expect friction.

**Comment by jdiaz5513** [comment]
Btw I recommend using the tsc lib since it'll be more likely to be portable
than anything involving a shell (I'm thinking of Windows, specifically).

**Comment by efokschaner** [comment]
Hey, it's been a while but I just wanted to let you know I have work in progress on `capnpc-js` and associated tests. It's actually running into failures in the schema deserialisation, so first bug found maybe? =D I hope to share soon.

**Comment by jdiaz5513** [comment]
Cool! I wonder if we found the same bug. I'll be making a bunch of pushes today in a granular approach to full test coverage, a bunch of them fix real bugs with the serialization.
