### ISSUE TITLE
Build instructions don't quite work

### ISSUE THREAD

**Issue by kentonv** [jdiaz5513/capnp-ts#52]
Starting from a fresh repo, I followed the instructions under "Building" in the readme, but they didn't quite work. The build failed as shown below.

I found that I was able to fix this problem by symlinking the directories under `packages` into the `node_modules` directory, in particular so that `capnp-ts` successfully resolved, but I presume that's not the "right" solution. Note that I haven't used Yarn, Gulp, or Typescript before, but have used npm and node plenty.

    kenton@zero:~/src/capnp-ts:master$ yarn install
    yarn install v0.27.5
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    [3/4] Linking dependencies...
    [4/4] Building fresh packages...
    Done in 2.57s.
    kenton@zero:~/src/capnp-ts:master$ npm run build
    
    > capnp-ts-all@0.0.1 build /home/kenton/src/capnp-ts
    > gulp build
    
    [12:52:17] Using gulpfile ~/src/capnp-ts/gulpfile.js
    [12:52:17] Starting 'build:capnp-ts:lib'...
    [12:52:19] Finished 'build:capnp-ts:lib' after 2.59 s
    [12:52:19] Starting 'build:capnpc-ts:lib'...
    
    5 import * as s from 'capnp-ts/lib/std/schema.capnp';
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
    packages/capnpc-ts/src/ast-creators.ts(5,20): error TS2307: Cannot find module 'capnp-ts/lib/std/schema.capnp'.
    
    
    6 import {format, pad} from 'capnp-ts/lib/util';
                                ~~~~~~~~~~~~~~~~~~~
    
    packages/capnpc-ts/src/ast-creators.ts(6,27): error TS2307: Cannot find module 'capnp-ts/lib/util'.
    
    
    5 import * as s from 'capnp-ts/lib/std/schema.capnp';
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
    packages/capnpc-ts/src/code-generator-file-context.ts(5,20): error TS2307: Cannot find module 'capnp-ts/lib/std/schema.capnp'.
    
    ... more similar errors follow ...

**Comment by kentonv** [comment]
`npm run test` fails with:

    packages/capnp-ts/test/unit/util.spec.ts(1,29): error TS2307: Cannot find module 'testcheck'.

**Comment by jdiaz5513** [comment]
You need to run `npm run bootstrap` first to have lerna link everything together and set up each package's `node_modules` folders - the README needs updating.

Try all of that again after running the `npm run bootstrap` command.

**Comment by kentonv** [comment]
Thanks, that worked.

Ah, the node dependency ecosystem...
