### ISSUE TITLE
Zero out objects that are no longer reachable

### ISSUE THREAD

**Issue by kentonv** [jdiaz5513/capnp-ts#54]
In the C++ implementation, any time a pointer is overwritten making the previously pointed-to object unreachable, said object is recursively overwritten with zeros.

This is important for two reasons:
- This situation unfortunately creates a "hole" in the message -- data that wastes space on the wire, but which isn't actually part of the message. There's no reasonable way to avoid a hole, but zeroing it out ensures that the hole compresses well, if any compression is applied.
- Application developers may not expect that data they thought they "removed" from the message may in fact still be present on the wire. This can be a security problem, if the data was intentionally removed to hide it from the eventual recipient. We have in fact seen real-world use cases where this was a security problem.

For these reasons I recommend implementing the C++ behavior in capnp-ts.

Note that orphans are tricky here. In C++, we have destructors, so if an orphan is destroyed without being adopted, we can automatically go zero out the object at that time. In Javascript you'll need an explicit `dispose()` method, I suppose. (Or if you are feeling evil, you could call it `euthanize()`...)

**Comment by jdiaz5513** [comment]
I believe I was careful with making sure this actually does happen, and Orphan does in fact have a [`dispose()`]() method.

Orphans are extra tricky to use in this JS version, since you do in fact need to remember to call `dispose()` for reasons beyond just a simple memory leak.

I'll leave this open for now as a reminder to explicitly test for erase behavior in a variety of cases.

**Comment by kentonv** [comment]
Hmm, yesterday I traced through the code path for setting a pointer and I didn't see where it zero'd out the old pointer. I therefore assumed this wasn't implemented, but I must have missed something.
