### ISSUE TITLE
Consider switching the test framework

### ISSUE THREAD

**Issue by ishitatsuyuki** [jdiaz5513/capnp-ts#55]
I found node-tap is quite minor and it doesn't integrate well with Gulp. Are you using any exclusive features from it? If so, feel free to close. If not, I would recommend switching to Jasmine.

I would like to do the migration for you too, if you want to focus on other things.

**Comment by jdiaz5513** [comment]
I am a huge fan of node-tape over jasmine/mocha, having used each extensively in the past.

What gulp "integration" is needed?

This article largely explains why I prefer it over Jasmine, consider it required reading: https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4

**Comment by ishitatsuyuki** [comment]
Does [ava](https://github.com/avajs/ava) looks good to you? Mainly, it has the same concepts as `tape` and I think it will fit your usage. Additionally, these issues with `node-tap` can be resolved:

- TypeScript definitions. `node-tap` isn't going to add it any time, but Ava already has one.
- `index.spec.ts` exports can be eliminated. Ava just use globs instead.

I'll happily create a PR if you agree to migrate. How do you think?
