### ISSUE TITLE
npm install not yielding results

### ISSUE THREAD

**Issue by Pooja71** [jdiaz5513/capnp-ts#62]
Hi,

I am trying to install the Js serialization and schema generation tools for capnp but none of the installation commands given in the READme work. 

ERROR:
npm ERR! code E404
npm ERR! 404 Not Found: capnpc-ts@latest

npm ERR! A complete log of this run can be found in:

Steps to reproduce:
npm install --save capnpc-js
or
npm install --save capnpc-ts
or 
npm install --save capnp-ts.

If there is any other way of installing it, please let me know. Also, I am primarily looking for JS implementation of compiling schema and deserializing the messages.

Any help would be appreciated.

**Comment by jdiaz5513** [comment]
It hasn't been published to NPM yet. :)

I'll publish what's on master in a few hours so you can take it for a spin, but beware of #46, which I'm currently working on. If you're just deserializing and building messages without adopting or overwriting pointers you should be totally OK, but please do report any quirks you encounter.

**Comment by Pooja71** [comment]
Thanks! Please let me know when you do. In the meanwhile can you tell me how are you or the others using the package directly from the source code? I am a complete noob when it comes to node.js and thus don't completely know the intricacies. Thanks in advance!

**Comment by jdiaz5513** [comment]
The packages are published now, so those npm commands should work.

Installing packages locally is pretty easy. Clone the source and run something like the following from your project's root directory:

```shell
~/my-js-project> npm install ~/path/to/capnp-ts/packages/capnp-ts
```

**Comment by Pooja71** [comment]
Ok, thanks a lot @jdiaz5513 ! Will keep you posted if I observe any weird behavior.
