### ISSUE TITLE
Unable to specify a path for the output file

### ISSUE THREAD

**Issue by Pooja71** [jdiaz5513/capnp-ts#64]
Hi @jdiaz5513 ,

Thanks for the npm publish. Your documentation mentions that the the  schema.capnp.js gets generated at the same path as the input schema.capnp. The default behavior of capnp compile allows the setting of an output path too. Is there a way I can avail that functionality here? I tried the following command:

capnp compile -o<path-to-capnpc-js.js>:<path-for-the ouptput-capnp.js> <path-to-schema.capnp>

Note: running capnpc-js throws error if an absolute path is given. You have to specify <path-to-bin>/bin/capnpc-js.js

Let me know if you have any imputs.

**Comment by jdiaz5513** [comment]
I'll revise the docs to note you have to path to /bin/capnpc-js.js; that is expected behavior if you don't have the package globally installed.

I was able to confirm that specifying an output directory does break things; I'll publish a patch today to fix it.

**Comment by jdiaz5513** [comment]
Closed by #67.
