### ISSUE TITLE
Int64 implementation

### ISSUE THREAD

**Issue by smoreinis** [jdiaz5513/capnp-ts#71]
There seems to be an issue with the two's complement implementation of the Int64 field type (or how I am using it).

Storing some value between 128 and 255 (say, 130) in a Uint64 works as expected but storing this in an Int64 returns a large negative number.
https://github.com/jdiaz5513/capnp-ts/blob/master/packages/capnp-ts/src/types/int64.ts#L197 seems to be negating the value based on the most significant bit of the least significant byte (which is 1 for values between 128 and 255) - is this a bug?

**Comment by jdiaz5513** [comment]
Ack! That does seem horribly broken.

`Int64.fromNumber(x).toNumber(x) === x` must always be true if `x <= Number.MAX_SAFE_INTEGER`; I'll check the test suite to see why this isn't being caught.

**Comment by jdiaz5513** [comment]
You were right on the money - L197 was wrong (facking little-endian, I intended to check the MSB). I'll have a patch pushed tonight. Thanks!
