### ISSUE TITLE
set(U)Int64 implementation

### ISSUE THREAD

**Issue by smoreinis** [jdiaz5513/capnp-ts#73]
Hi!

Thanks so much for fixing the previous int64 issue so quickly. I believe I ran into another bug trying to actually write these int64 values to the capnp message.

For example, writing capnp.Uint64.fromNumber(Math.pow(500000, 2)) into a Uint64 field and reading it out returns 891896832 (instead of 250000000000 which is still well under the max value).

I investigated this a little bit and it seems like https://github.com/jdiaz5513/capnp-ts/blob/master/packages/capnp-ts/src/serialization/segment.ts#L451 could be the culprit - `val.buffer` is actually a Uint8 array of length 8 but only the first half of it seems to be getting set. Replacing this with e.g. 
```
for (var i = 0; i < val.buffer.length; ++i) {
  this._dv.setUint8(byteOffset + i, val.buffer[i]);
}
```
seemed to do the trick and fix the issue I was seeing. https://github.com/jdiaz5513/capnp-ts/blob/master/packages/capnp-ts/src/serialization/segment.ts#L405 seems to have a similar issue although I haven't personally verified that one yet. 

Let me know if you have any questions or other suggestions to work around this.

**Comment by jdiaz5513** [comment]
Oof. Right on the money again. This is what happens when you give up on 100% test coverage. 😓

I'll have it patched soon.

**Comment by jdiaz5513** [comment]
v0.1.5 pushed, thanks for the help. Hopefully I'll catch more of these myself as I work on RPC this month.

**Comment by smoreinis** [comment]
Thanks so much for the quick turnaround!

**Comment by smoreinis** [comment]
@jdiaz5513 maybe a noob question - but when I npm install and see the 0.1.5 version show up, `src/serialization/segment.ts` has the fix but `lib/serialization/segment.js` does not (and has a modified date of 0ct 18 still which looks like 0.1.4). 
I'm using this library from JS and it looks like I'm still hitting the same issue - is the lib vs. src discrepancy something that should sort itself out over time or is there an explicit compilation of src into lib that needs to happen?

**Comment by smoreinis** [comment]
Ping - any suggestions? Still seeing this from a fresh `npm install capnp-ts`.

**Comment by jdiaz5513** [comment]
One of the publish scripts didn't work as expected, darn. I'll push up
0.1.6 soon.

**Comment by jdiaz5513** [comment]
Give 0.1.6 a shot, let me know if it's still farked.

**Comment by smoreinis** [comment]
Works now! Thank you.
