### ISSUE TITLE
capnp imports

### ISSUE THREAD

**Issue by smoreinis** [jdiaz5513/capnp-ts#75]
Didn't see anything mentioning imports (or lack of support for them) in the README, so just wanted to document the behavior I'm seeing.

I created `bar.capnp` as follows:
```
struct Baz {
  bar @0 :Text;
}
```

I then tried to use this `Baz` message type from `foo.capnp`. Here are some of the attempts (based on the three variants listed at https://capnproto.org/language.html):
```
using Bar = import "bar.capnp";
struct Foo {
  baz @0 :import "bar.capnp".Baz;
}
```

```
using Bar = import "bar.capnp";
struct Foo {
  baz @0 :Bar.Baz;
}
```

```
using import "bar.capnp".Baz;
struct Foo {
  baz @0 :Baz;
}
```

For either of these three versions, `capnpc -o js foo.capnp` fails with `foo.capnp.ts:13:34 Cannot find name 'Baz'.` errors. Best I can tell, the generated .ts files don't map the import statements to any includes of the .capnp.ts files and so compiling that to JS fails.

Is there a working version of imports available now? If not, is it on the roadmap? Thanks!

**Comment by jdiaz5513** [comment]
It's not implemented in the schema compiler, and obviously quite important!

I'll bump it up as the next thing to implement.
