### ISSUE TITLE
Importing c++.capnp

### ISSUE THREAD

**Issue by smoreinis** [jdiaz5513/capnp-ts#81]
Hi!

Very happy to see that imports have been fixed in the latest release. 
I ran into an issue trying to compile a schema that includes https://github.com/capnproto/capnproto/blob/master/c%2B%2B/src/capnp/c%2B%2B.capnp

Here's an example file:
```
using Cxx = import "c++.capnp";
$Cxx.namespace("Initrode");

struct Foo {
  bar @0 :Text;
}
```

which returns `Error: CAPNPC-TS002 Failed to look up node id Infinity.` when compiling.

**Comment by jdiaz5513** [comment]
Should be fixed in #82.

There's bound to be more rough edges in the compiler.

I'm going to throw [this whopper](https://github.com/capnproto/capnproto/blob/master/c%2B%2B/src/capnp/test.capnp) at the compiler and turn it into a test suite, that should shake out a ton of bugs fast.
