### ISSUE TITLE
'capnp' is declared but its value is never read

### ISSUE THREAD

**Issue by smoreinis** [jdiaz5513/capnp-ts#83]
Having updated to 0.2.2 with the c++.capnp fix, I realized I'm actually having issues generating JS files for even the most basic of schemas. 
Trying to compile bar.capnp from https://github.com/jdiaz5513/capnp-ts/issues/75 yields: 
```
bar.capnp.ts:7:13 'capnp' is declared but its value is never read.
bar.capnp.ts:7:13 'capnp' is declared but its value is never read.
Error: CAPNPC-TS008 Failed to transpile emitted schema source code; see above for error messages.
```

Is there some extra TS code being generated after the refactor that's getting caught in the transpile step?

**Comment by jdiaz5513** [comment]
The compiler options are too strict for capnpc-js. Patch incoming!

**Comment by jdiaz5513** [comment]
Look out for canpc-js v0.2.3, should solve your problem.

Appreciate the patience and diligence with filing bugs. Feel free to submit a PR to add yourself to `HUMANS.md` as an early adopter at the very least. :)

**Comment by smoreinis** [comment]
Thanks! Appreciate your patience and diligence in fixing them :) 
I'll definitely add myself next time I see an easy fix I can submit a PR for at the very least :D
