### ISSUE TITLE
capnpc-js 0.2.3 has old capnpc-js/lib/index.js

### ISSUE THREAD

**Issue by smoreinis** [jdiaz5513/capnp-ts#85]
After updating capnpc-js to v0.2.3, I see that capnpc-js/src/index.ts has
```
  noUnusedLocals: false,
  noUnusedParameters: false,
```
but capnpc-js/lib/index.js still has
```
        noUnusedLocals: true,
        noUnusedParameters: true,
```
which causes https://github.com/jdiaz5513/capnp-ts/issues/83 to continue happening.

**Comment by jdiaz5513** [comment]
Don't know how that could have happened, but I did a full republish with 0.2.4 so give that version a shot.

**Comment by smoreinis** [comment]
Thanks! Updated to 0.2.4 and I'm seeing foo.capnp compile again now.
