### ISSUE TITLE
hasThing is true, getThing fails.

### ISSUE THREAD

**Issue by ChristopherBiscardi** [jdiaz5513/capnp-ts#90]
Hey, I'm trying to use this lib from JS and I'm running into a weird error relating to `has*` reporting true and `get*` failing. My node session looks something like this:

```
> const msg = new capnp.Message(BIN_DATA, false);
> const events = msg.getRoot(STRUCTS.Event);
> events.hasInitData()
true
> events.getInitData()
Error: CAPNP-TS018 Attempted to access getter on Event_Struct_Pointer_0@0x00000000,[00 00 00 00 02 00 01 00],limit:0x7fffffff for union field initData that is not currently set (wanted: 23, found: 0).
```

Is there something specific I should be looking for with respect to debugging this?

**Comment by jdiaz5513** [comment]
You could be running into an unimplemented feature in the schema compiler.

Assuming they have no sensitive information, can you attach the .capnp schema file for `STRUCTS` and a dump of `BIN_DATA`?

I should be able to take a close look this weekend.

**Comment by ChristopherBiscardi** [comment]
# [acura-cap.zip](https://github.com/jdiaz5513/capnp-ts/files/1627179/acura-cap.zip)

includes:

* acura-capnp-log (BIN data)
* acura-capnp-log-decoded.txt (result of following decode)

```shell
capnp decode ./carlog.capnp Event < acura-capnp-log > acura-capnp-log-decoded.txt
```

* carlog.capnp
* carlog.capnp.js (result of following script in package.json)

```shell
capnpc -o js ./tmp/carlog.capnp
```

**Comment by ChristopherBiscardi** [comment]
`carlog.capnp` is a combined version of two other .capnp files (`car.capnp` and `log.capnp`) because there was an import issue with one of the generated enums (was planning on digging into the lib later to try to fix this but for now manually combining the two files worked fine).

Just realized you'll also probably need these two additional files if you try to compile the capnp files.
 [c-java.zip](https://github.com/jdiaz5513/capnp-ts/files/1627198/c-java.zip)

**Comment by jdiaz5513** [comment]
Strange, I can't reproduce this one!

I have two theories:
- Something might be up with the way you're reading `BIN_DATA`. Because of how dense the binary messages tend to be there isn't a lot of room to perform sanity checks on a blob of bytes that may or may not contain a capnp message.
- Maybe the latest version of capnp-ts or capnpc-ts published on NPM is borked somehow; the learning curve with `lerna publish` has not been kind to me.

This is the regression case I came up with:

```typescript
import { Event } from './carlog.capnp';
import { readFileBuffer, tap } from '../../util/index';
import * as capnp from '../../../lib';
import * as path from 'path';
import { readFileSync } from 'fs';

tap.test('carlog regression test', (t) => {

  const BIN_DATA = readFileSync(path.join(__dirname, '../../../test/integration/carlog/acura-capnp-log'));

  const events = new capnp.Message(BIN_DATA, false).getRoot(Event);

  t.ok(events.hasInitData());

  t.notThrow(events.getInitData);

  t.end();

});
```

No crash here. I'm even able to read arbitrary data off that `InitData` struct and it matches the decoded version exactly.

Can you try running off the latest master commit?

**Comment by ChristopherBiscardi** [comment]
Running the latest master seems to work (as does the latest npm). Must have been an error reading the file in. 

Thanks for taking the time to look into this (and the regression case). Going to close the issue.
